---
- hosts: r2
  gather_facts: no
  tasks:
    - name: trunk 0/0/0 sw1
      cisco.ios.ios_config:
        parents: "interface gi0/0/0"
        lines:
          - "no shutdown"

    - name: trunk 0/0/0.99 sw1
      cisco.ios.ios_config:
        parents: "interface gi0/0/0.99"
        lines:
          - "encapsulation dot1Q 99"
          - "ip address 10.0.99.3 255.255.255.0"
          - "standby version 2"
          - "standby 10 ip 10.0.99.1"
          - "no shutdown"

    - name: trunk 0/0/1 sw2
      cisco.ios.ios_config:
        parents: "interface gi0/0/1"
        lines:
          - "no shutdown"

    - name: trunk 0/0/1.10 HSRP sw2
      cisco.ios.ios_config:
        parents: "interface gi0/0/1.10"
        lines:
          - "encapsulation dot1Q 10"
          - "ip address 10.1.10.3 255.255.255.0"
          - "standby version 2"
          - "standby 20 ip 10.1.10.1"
          - "no shutdown"

    - name: trunk 0/0/1.20 HSRP sw2
      cisco.ios.ios_config:
        parents: "interface gi0/0/1.20"
        lines:
          - "encapsulation dot1Q 20"
          - "ip address 10.1.20.3 255.255.255.0"
          - "standby version 2"
          - "standby 30 ip 10.1.20.1"
          - "no shutdown"

    - name: trunk 0/0/1.99 sw2
      cisco.ios.ios_config:
        parents: "interface gi0/0/1.99"
        match: exact
        lines:
          - "encapsulation dot1Q 99"
          - "ip address 10.1.99.3 255.255.255.0"
          - "standby version 2"
          - "standby 40 ip 10.1.99.1"
          - "no shutdown"
  
    - name: acl 99
      cisco.ios.ios_config:
        lines:
        match: line
        replace: line
          - "access-list 99 permit 10.0.99.0 0.0.0.255"
          - "access-list 99 deny any"

    - name: vty 0-15 with acl
      cisco.ios.ios_config:
        parents: line vty 0 15
        lines: 
        match: line
        replace: line
          - "exec-timeout 10 0"
          - "transport input ssh"
          - "login local"
          - "access-class 99 in"

    - name: block multiple vlan to mgmt-vlan
      cisco.ios.ios_config:
        paretns: ip access-list extended protect_v99
        lines:       
        match: line
        replace: line
          - "deny ip any 10.1.99.0 0.0.0.255"
          - "deny ip any 10.0.99.0 0.0.0.255"
          - "permit ip any any"

    
    - name: apply acl on L3 interface 0.0.0.99
      cisco.ios.ios_config:
        parents: interface GigabitEthernet0/0/0.99
        line:
        match: line
        replace: line
          - "ip access-group protect_v99 out"

    - name: apply acl on L3 interface 0.0.1.99
      cisco.ios.ios_config:
        parents: interface GigabitEthernet0/0/1.99
        line:
        match: line
        replace: line
          - "ip access-group protect_v99 out"