---
- hosts: sw1
  gather_facts: no
  tasks:
    - name: hostname
      cisco.ios.ios_hostname:
        config: 
          hostname: SW1

    - name: add vlan 99
      cisco.ios.ios_vlans:
        config:
          - name: MGMT
            state: active
            vlan_id: 99
            shutdown: disabled
        state: merged

    - name: trunk r1 and r2
      cisco.ios.ios_config:
        parents: "interface range GigabitEthernet1/0/23 - 24"
        lines:
          - "switchport"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 99"
          - "no shutdown"