---
- hosts: sw2
  gather_facts: no
  tasks:
    - name: vlan
      cisco.ios.ios_config:
        lines:
          - "vlan 10"
          - "name STUD1"
          - "vlan 20"
          - "name STUD 2"

    - name: etherchannel
      cisco.ios.ios_config:
        parents: "interface range gi0/21 - 22"
        lines:
          - "channel-group 10 mode active"
          - "switchport"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: port-channel 10
      cisco.ios.ios_config:
        parents: "interface port-channel10"
        lines:
          - "switchport"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: trunk r1,r2
      cisco.ios.ios_config:
        parents: "interface range gi0/0/23 - 24"
        lines:
          - "switchport"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"