---
- hosts: sw2
  gather_facts: no
  tasks:
    - name: hostname
      cisco.ios.ios_hostname:
        config: 
          hostname: SW2

    - name: add vlan 10,20,99
      cisco.ios.ios_vlans:
        config:
          - name: MGMT
            state: active
            vlan_id: 99
            shutdown: disabled
          - name: STUD1
            state: active
            vlan_id: 10
            shutdown: disabled
          - name: STUD2
            state: active
            vlan_id: 20
            shutdown: disabled
        state: merged

    - name: port-channel 6
      cisco.ios.ios_config:
        parents: "interface port-channel6"
        lines:
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: etherchannelfa21
      cisco.ios.ios_config:
        parents: "interface fa0/21"
        lines:
          - "channel-group 6 mode active"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: etherchannel22
      cisco.ios.ios_config:
        parents: "interface fa0/22"
        lines:
          - "channel-group 6 mode active"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: trunk r1,r2
      cisco.ios.ios_config:
        parents: "interface range fa0/23-24"
        lines:
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"