---
- hosts: access
  gather_facts: no
  tasks:
    - name: vlan
      cisco.ios.ios_config:
        lines:
          - "vlan 10"
          - "name STUD1"
          - "vlan 20"
          - "name STUD2"

    - name: uplink to agg
      cisco.ios.ios_config:
        parents: "interface gi1/0/24"
        lines:
          - "switchport"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: access-ports vlan 10
      cisco.ios.ios_config:
        parents: "interface gi1/0/1"
        lines:
          - "switchport mode access"
          - "switchport access vlan 10"
          - "no shutdown"

    - name: access-ports vlan 20
      cisco.ios.ios_config:
        parents: "interface gi1/0/2"
        lines:
          - "switchport mode access"
          - "switchport access vlan 20"
          - "no shutdown"

    - name: acl 99
      cisco.ios.ios_config:
        lines:
        match: line
        replace: line
          - "access-list 99 permit 10.0.99.0 0.0.0.255"
          - "access-list 99 deny any"

    - name: vty 0-15 with acl
      cisco.ios.ios_config:
        parents: line vty 0 15
        lines: 
        match: line
        replace: line
          - "exec-timeout 10 0"
          - "transport input ssh"
          - "login local"
          - "access-class 99 in"