---
- hosts: access
  gather_facts: no
  tasks:
    - name: add vlan 10,20,99
      cisco.ios.ios_vlans:
        config:
          - name: MGMT
            state: active
            vlan_id: 99
            shutdown: disabled
          - name: STUD1
            state: active
            vlan_id: 10
            shutdown: disabled
          - name: STUD2
            state: active
            vlan_id: 20
            shutdown: disabled
        state: merged

    - name: uplink to agg
      cisco.ios.ios_config:
        parents: "interface gi1/0/24"
        lines:
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,99"
          - "no shutdown"

    - name: access-ports vlan 10
      cisco.ios.ios_config:
        parents: "interface gi1/0/1"
        lines:
          - "switchport mode access"
          - "switchport access vlan 10"
          - "spanning-tree portfast"
          - "no shutdown"

    - name: access-ports vlan 20
      cisco.ios.ios_config:
        parents: "interface gi1/0/2"
        lines:
          - "switchport mode access"
          - "switchport access vlan 20"
          - "spanning-tree portfast"
          - "no shutdown"